 -- Q1. What is the total revenue generated by male vs female customers?

 select gender, SUM(purchase_amount) as revenue
from customer
group by gender

-- Q2. Which customers use a discount but still spent more than the average purchase amount?

Select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >=
(select AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?

Select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Review Rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5;

--Q4. Compare the average purchase amounts between standard and express shipping.

select shipping_type,
ROUND(AVG(purchase_amount),2) 
from customer
where shipping_type IN ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers.

select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spent,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer
group by subscription_status
order by total_revenue, avg_spent desc;


--Q6. 

select item_purchased,
ROUND(100* SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning and loyal based on their total 
-- number of purchases, and show the count of each segment.

with customer_type as( 
select customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	Else 'Loyal' 
	END as customer_segment
from customer
)

Select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment


-- Q8. What are the top 3 most purchased products within each category?

with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(partition by category order by COUNT(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)
Select item_rank, category, item_purchased, total_orders
from item_counts
Where item_rank <=3;

--Q9. Are customers who are repeat buyers( more than 5 previous purchases) also likely to subscribe.

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status

--Q10. What is the revenue contribution of each age group?

select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc